/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CreateUserRespData struct {
	// Status (1=not opened, 2=pending review, 3=opened)
	Status int32 `json:"status,omitempty"`
	// leverage
	Leverage int32 `json:"leverage,omitempty"`
	// mt5uid
	Mt5Uid string `json:"mt5_uid,omitempty"`
}
