/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type DualProjectRecommend struct {
	// Product ID
	Id int64 `json:"id,omitempty"`
	// Strategy category
	Category int32 `json:"category,omitempty"`
	// `call`: sell high; `put`: buy low
	Type string `json:"type,omitempty"`
	// Investment Token
	InvestCurrency string `json:"invest_currency,omitempty"`
	// Strike Token
	ExerciseCurrency string `json:"exercise_currency,omitempty"`
	// Annual Yield
	ApyDisplay string `json:"apy_display,omitempty"`
	// Strike price
	ExercisePrice string `json:"exercise_price,omitempty"`
	// Settlement time
	DeliveryTimest int64 `json:"delivery_timest,omitempty"`
	// Minimum investment amount
	MinAmount string `json:"min_amount,omitempty"`
	// Maximum investment amount
	MaxAmount string `json:"max_amount,omitempty"`
	// Minimum Units
	MinCopies int64 `json:"min_copies,omitempty"`
	// Maximum Units
	MaxCopies int64 `json:"max_copies,omitempty"`
	// Lock-up days
	InvestDays int64 `json:"invest_days,omitempty"`
	// Lock-up hours
	InvestHours string `json:"invest_hours,omitempty"`
}
