/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Options contract details
type OptionsTicker struct {
	// Options contract name
	Name string `json:"name,omitempty"`
	// Last trade price (quote currency)
	LastPrice string `json:"last_price,omitempty"`
	// Current mark price (quote currency)
	MarkPrice string `json:"mark_price,omitempty"`
	// Current index price (quote currency)
	IndexPrice string `json:"index_price,omitempty"`
	// Best ask size
	Ask1Size int64 `json:"ask1_size,omitempty"`
	// Best ask price
	Ask1Price string `json:"ask1_price,omitempty"`
	// Best bid size
	Bid1Size int64 `json:"bid1_size,omitempty"`
	// Best bid price
	Bid1Price string `json:"bid1_price,omitempty"`
	// Current total long position size
	PositionSize int64 `json:"position_size,omitempty"`
	// Implied volatility
	MarkIv string `json:"mark_iv,omitempty"`
	// Bid side implied volatility
	BidIv string `json:"bid_iv,omitempty"`
	// Ask side implied volatility
	AskIv string `json:"ask_iv,omitempty"`
	// Leverage = underlying_price / (mark_price * delta). This value is for reference only.
	Leverage string `json:"leverage,omitempty"`
	// Greek letter delta
	Delta string `json:"delta,omitempty"`
	// Greek letter gamma
	Gamma string `json:"gamma,omitempty"`
	// Greek letter vega
	Vega string `json:"vega,omitempty"`
	// Greek letter theta
	Theta string `json:"theta,omitempty"`
	// Rho
	Rho string `json:"rho,omitempty"`
}
