/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type Currency struct {
	// Currency symbol
	Currency string `json:"currency,omitempty"`
	// Currency name
	Name string `json:"name,omitempty"`
	// Whether currency is de-listed
	Delisted bool `json:"delisted,omitempty"`
	// Whether currency's withdrawal is disabled (deprecated)
	WithdrawDisabled bool `json:"withdraw_disabled,omitempty"`
	// Whether currency's withdrawal is delayed (deprecated)
	WithdrawDelayed bool `json:"withdraw_delayed,omitempty"`
	// Whether currency's deposit is disabled (deprecated)
	DepositDisabled bool `json:"deposit_disabled,omitempty"`
	// Whether currency's trading is disabled
	TradeDisabled bool `json:"trade_disabled,omitempty"`
	// Fixed fee rate. Only for fixed rate currencies, not valid for normal currencies
	FixedRate string `json:"fixed_rate,omitempty"`
	// The main chain corresponding to the coin
	Chain string `json:"chain,omitempty"`
	// All links corresponding to coins
	Chains []SpotCurrencyChain `json:"chains,omitempty"`
	// Total supply
	TotalSupply string `json:"total_supply,omitempty"`
	// Market cap
	MarketCap string `json:"market_cap,omitempty"`
	// 币种分类  - stocks: 股票 - metals: 金属 - indices: 指数 - forex: 外汇 - commodities: 大宗商品
	Category []string `json:"category,omitempty"`
}
