/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineObject2 struct {
	// BUY for on-ramp, SELL for off-ramp
	Type string `json:"type"`
	// Quote direction returned by the quote API (used for order validation)
	Side string `json:"side"`
	// Cryptocurrency (supported currencies can be queried from the OTC web fiat quote page)
	CryptoCurrency string `json:"crypto_currency"`
	// Fiat currency (supported currencies can be queried from the OTC web fiat quote page)
	FiatCurrency string `json:"fiat_currency"`
	// Amount of cryptocurrency
	CryptoAmount string `json:"crypto_amount"`
	// Fiat amount
	FiatAmount string `json:"fiat_amount"`
	// Promotion code
	PromotionCode string `json:"promotion_code,omitempty"`
	// Parameter returned by the quote API
	QuoteToken string `json:"quote_token"`
	// Bank card ID used for the order (retrieved via the default bank card API)
	BankId string `json:"bank_id"`
}
