/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type ExchangesDataList struct {
	// Trading market, supports us, hk, and kr
	Exchange string `json:"exchange,omitempty"`
	// Market display name
	ExchangeDesc string `json:"exchange_desc,omitempty"`
	// Market icon
	IconLink string `json:"icon_link,omitempty"`
	// Whether stock transfer is supported
	SupportTransfer bool `json:"support_transfer,omitempty"`
}
