/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// File pre-upload request body
type OtcUploadPreUploadRequest struct {
	// **Base64** of the file MIME type, required. Only image/png, image/jpeg, image/jpg, and application/pdf are supported.
	ContentType string `json:"content_type"`
	// Business scene, optional, defaults to general; determines temporary path and production directory after relocation
	Scene string `json:"scene,omitempty"`
}
