/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Send chat message request
type SendChatMessageRequest struct {
	// Order ID
	Txid int32 `json:"txid"`
	// Message type: `0` text; `1` file (image or video); defaults to `0`.
	Type int32 `json:"type,omitempty"`
	// Message content. When type=0, pass text up to 500 characters, which goes through off-platform traffic diversion risk control; when hit, the response contains risk_type=1 and toast_msg. When type=1, pass the file_key returned by upload_chat_file
	Message string `json:"message"`
}
