/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CandyDropV4ParticipationRecordCd05 struct {
	// Activity ID
	Id int64 `json:"id,omitempty"`
	// Product Name
	Currency string `json:"currency,omitempty"`
	// Project status: ongoing/awaiting_draw/won/not_win
	Status string `json:"status,omitempty"`
	// Participation time (UTC formatted)
	RegisterTime string `json:"register_time,omitempty"`
}
