/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Business data
type FlashSwapMultiCurrencyOneToManyOrderPreviewRespData struct {
	// Preview order list
	Orders []FlashSwapMultiCurrencyPreviewOrder `json:"orders"`
	// Total consumed amount
	TotalConsumeAmount string `json:"total_consume_amount"`
	// Total amount received
	TotalAcquireAmount string `json:"total_acquire_amount"`
}
