/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse20042 struct {
	// User ID
	UserId string `json:"userId"`
	// Trading Pair
	Symbol string `json:"symbol"`
	// Interest Deduction ID
	InterestId string `json:"interest_id"`
	// Debt Source ID, can be Order ID or Position ID
	LiabilityId string `json:"liability_id"`
	// Debt Quantity
	Liability string `json:"liability"`
	// Debt Currency
	LiabilityCoin string `json:"liability_coin"`
	// Interest
	Interest string `json:"interest"`
	// interest rate
	InterestRate string `json:"interest_rate"`
	// Interest deduction type (`PERIODIC_POSITION`: periodic position interest; `PERIODIC_OPEN_ORDER`: periodic open-order interest; `IMMEDIATE_OPEN_ORDER`: interest charged on order opening)
	InterestType string `json:"interest_type"`
	// Created time
	CreateTime string `json:"create_time"`
	// Exchange
	ExchangeType string `json:"exchange_type"`
}
