/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Trail order modification records
type TrailChangeLog struct {
	// Update time
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// Trading quantity in contracts, positive for buy, negative for sell
	Amount string `json:"amount,omitempty"`
	// true: activate when market price >= activation price, false: <= activation price
	IsGte bool `json:"is_gte,omitempty"`
	// Activation price, 0 means trigger immediately
	ActivationPrice string `json:"activation_price,omitempty"`
	// Activation price type: 0-unknown, 1-latest price, 2-index price, 3-mark price
	PriceType int32 `json:"price_type,omitempty"`
	// Callback ratio or price distance, e.g., `0.1` or `0.1%`
	PriceOffset string `json:"price_offset,omitempty"`
	// true - order creation, false - order modification
	IsCreate bool `json:"is_create,omitempty"`
}
