/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Empty object when the advertisement is published or edited successfully; returns risk details when the advertisement content hits risk control
type P2pMerchantBooksPlaceBizPushOrderResponseData struct {
	// Risk control sub-code; 0 for advertisement content traffic diversion risk control
	RiskCode  int32                                                  `json:"risk_code,omitempty"`
	RiskEvent P2pMerchantBooksPlaceBizPushOrderResponseDataRiskEvent `json:"risk_event,omitempty"`
}
