/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type LaunchPoolV4RewardRecord struct {
	// Reward date
	RewardTimest string `json:"reward_timest"`
	// Reward currency
	Coin string `json:"coin"`
	// Active pledge count
	ValidMortgageAmount string `json:"valid_mortgage_amount"`
	// Base airdrop
	AmountBase string `json:"amount_base"`
	// Bonus airdrop
	AmountExt string `json:"amount_ext"`
}
