/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UnifiedBalance struct {
	// Available balance, valid in single currency margin/cross-currency margin/combined margin mode, calculation varies by mode
	Available string `json:"available,omitempty"`
	// Locked balance, valid in single currency margin/cross-currency margin/combined margin mode
	Freeze string `json:"freeze,omitempty"`
	// Borrowed amount, valid in cross-currency margin/combined margin mode, 0 in other modes such as single-currency margin mode
	Borrowed string `json:"borrowed,omitempty"`
	// Negative balance borrowing, valid in cross-currency margin/combined margin mode, 0 in other modes such as single-currency margin mode
	NegativeLiab string `json:"negative_liab,omitempty"`
	// Contract opening position borrowing currency (abandoned, to be offline field)
	FuturesPosLiab string `json:"futures_pos_liab,omitempty"`
	// Equity, valid in single currency margin/cross currency margin/combined margin mode
	Equity string `json:"equity,omitempty"`
	// Total frozen (deprecated, to be removed)
	TotalFreeze string `json:"total_freeze,omitempty"`
	// Total borrowed amount, valid in cross-currency margin/combined margin mode, 0 in other modes such as single-currency margin mode
	TotalLiab string `json:"total_liab,omitempty"`
	// The amount of spot hedging is valid in the combined margin mode, and is 0 in other margin modes such as single currency and cross-currency margin modes
	SpotInUse string `json:"spot_in_use,omitempty"`
	// Uniloan financial management amount, effective when turned on as a unified account margin switch
	Funding string `json:"funding,omitempty"`
	// Funding version
	FundingVersion string `json:"funding_version,omitempty"`
	// Full margin balance is valid in single currency margin mode, and is 0 in other modes such as cross currency margin/combined margin mode
	CrossBalance string `json:"cross_balance,omitempty"`
	// Isolated Margin Balance applies to Single-Currency Margin Mode and Cross-Currency Margin Mode, and is 0 in other modes such as Portfolio Margin Mode.
	IsoBalance string `json:"iso_balance,omitempty"`
	// Full-position initial margin is valid in single-currency margin mode and is 0 in other modes such as cross-currency margin/combined margin mode
	Im string `json:"im,omitempty"`
	// Cross margin maintenance margin, valid in single-currency margin mode, 0 in other modes such as cross-currency margin/combined margin mode
	Mm string `json:"mm,omitempty"`
	// Full-position initial margin rate is valid in single-currency margin mode and is 0 in other modes such as cross-currency margin/combined margin mode
	Imr string `json:"imr,omitempty"`
	// Full-position maintenance margin rate is valid in single-currency margin mode and is 0 in other modes such as cross-currency margin/combined margin mode
	Mmr string `json:"mmr,omitempty"`
	// Full margin balance is valid in single currency margin mode and is 0 in other modes such as cross currency margin/combined margin mode
	MarginBalance string `json:"margin_balance,omitempty"`
	// Cross margin available balance, valid in single currency margin mode, 0 in other modes such as cross-currency margin/combined margin mode
	AvailableMargin string `json:"available_margin,omitempty"`
	// Currency enabled as margin: true - Enabled, false - Disabled
	EnabledCollateral bool `json:"enabled_collateral,omitempty"`
}
