/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type TransactionItem struct {
	// Asset
	Asset string `json:"asset,omitempty"`
	// Symbol
	Symbol string `json:"symbol,omitempty"`
	// Symbol display name
	SymbolDisplay string `json:"symbol_display,omitempty"`
	// Transaction type. - deposit: Funds transfer in. - withdraw: Funds transfer out. - fee: Trading fee. - dividend: Dividend payout. - sell: Stock sale credit. - buy: Stock purchase debit. - award: Airdrop reward. - stock_transfer_in: Stock transfer in. - stock_transfer_out: Stock transfer out.
	Type string `json:"type,omitempty"`
	// Transaction type description
	TypeDesc string `json:"type_desc,omitempty"`
	// Change amount
	Change string `json:"change,omitempty"`
	// Balance after change
	Balance string `json:"balance,omitempty"`
	// Business idempotent ID
	RefId string `json:"ref_id,omitempty"`
	// Unix timestamp (seconds)
	Time int64 `json:"time,omitempty"`
	// Unit display text
	UnitText string `json:"unit_text,omitempty"`
	// Business details
	Detail map[string]map[string]interface{} `json:"detail,omitempty"`
}
