/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// User participation record single item
type HodlerAirdropV4UserOrderRecord struct {
	// Product ID
	HodlerId string `json:"hodler_id"`
	// Airdrop currency
	Asset string `json:"asset"`
	// Effective number of GT positions (average number of GT held when participating in the event)
	UserGtAvgAmount string `json:"user_gt_avg_amount,omitempty"`
	// Basic airdrop amount, it will be an empty string before the end of the activity
	ReceiveAmountBase string `json:"receive_amount_base,omitempty"`
	// Additional airdrop amount (Yubibao bonus), it will be an empty string before the end of the event
	ReceiveAmountExt string `json:"receive_amount_ext,omitempty"`
	// Event end time, format Y-m-d H:i:s, UTC
	CloseTimest string `json:"close_timest"`
}
