/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Get my ads list request
type MyAdsListRequest struct {
	// Cryptocurrency
	Asset string `json:"asset,omitempty"`
	// Fiat currency
	FiatUnit string `json:"fiat_unit,omitempty"`
	// Buy/Sell
	TradeType string `json:"trade_type,omitempty"`
}
