/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Small Balance Conversion
type SmallBalanceHistory struct {
	// Order ID
	Id string `json:"id,omitempty"`
	// Currency
	Currency string `json:"currency,omitempty"`
	// Swap Amount
	Amount string `json:"amount,omitempty"`
	// GT amount
	GtAmount string `json:"gt_amount,omitempty"`
	// Exchange time (in seconds)
	CreateTime int64 `json:"create_time,omitempty"`
}
