/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type LedgerRecord struct {
	// Record ID
	Id string `json:"id,omitempty"`
	// Hash record of the withdrawal
	Txid string `json:"txid,omitempty"`
	// User-defined order number for withdrawal. Default is empty. When not empty, the specified user-defined order number record will be queried
	WithdrawOrderId string `json:"withdraw_order_id,omitempty"`
	// Operation time
	Timestamp string `json:"timestamp,omitempty"`
	// Token amount
	Amount string `json:"amount"`
	// Currency name
	Currency string `json:"currency"`
	// Withdrawal address. Required for withdrawals
	Address string `json:"address,omitempty"`
	// Additional remarks with regards to the withdrawal
	Memo string `json:"memo,omitempty"`
	// Withdrawal record ID starts with 'w', such as: w1879219868. When withdraw_id is not empty, only this specific withdrawal record will be queried, and time-based querying will be disabled
	WithdrawId string `json:"withdraw_id,omitempty"`
	// Withdrawal record currency type, empty by default. Supports users to query withdrawal records in main area and innovation area on demand. Valid values: SPOT, PILOT  SPOT: Main area PILOT: Innovation area
	AssetClass string `json:"asset_class,omitempty"`
	// Transaction status  - DONE: Completed - CANCEL: Cancelled - REQUEST: Requesting - MANUAL: Pending manual review - BCODE: GateCode operation - EXTPEND: Sent, waiting for confirmation - FAIL: Failed on chain, waiting for confirmation - INVALID: Invalid order - VERIFY: Verifying - PROCES: Processing - PEND: Processing - DMOVE: Pending manual review - REVIEW: Under review
	Status string `json:"status,omitempty"`
	// Name of the chain used in withdrawals
	Chain string `json:"chain"`
}
