/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CrossexAccountBookRecord struct {
	// Account Change Record ID
	Id string `json:"id"`
	// User ID
	UserId string `json:"user_id"`
	// Business ID
	BusinessId string `json:"business_id"`
	// Change type | `TRANSACTION` trade `TRADING_FEE` fee `FUNDING_FEE` futures funding fee `LIQUIDATION_FEE` liquidation fee `TRANSFER_IN` transfer in `TRANSFER_OUT` transfer out `BANKRUPT_COMPENSATION` bankruptcy compensation `AUTO_REPAY` margin position auto-repay
	Type string `json:"type"`
	// Exchange
	ExchangeType string `json:"exchange_type"`
	// Currency
	Coin string `json:"coin"`
	// Change amount (positive indicates transfer in; negative indicates transfer out)
	Change string `json:"change"`
	// Balance after change
	Balance string `json:"balance"`
	// Created time
	CreateTime string `json:"create_time"`
}
