/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// ETH Mining
type Eth2Swap struct {
	// 1-Forward Swap (ETH -> GTETH), 2-Reverse Swap (GTETH -> ETH)
	Side string `json:"side"`
	// Swap Amount
	Amount string `json:"amount"`
}
