/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Place ad order request
type PlaceBizPushOrder struct {
	// Cryptocurrency symbol.
	CurrencyType string `json:"currencyType"`
	// Fiat currency
	ExchangeType string `json:"exchangeType"`
	// Ad operation type. `0`: publish sell ad; `1`: publish buy ad; `2`: edit sell ad; `3`: edit buy ad.
	Type string `json:"type"`
	// Per-unit price in fixed-price mode.
	UnitPrice string `json:"unitPrice"`
	// Ad amount priced in `currencyType`.
	Number string `json:"number"`
	// Payment types, comma-separated; from pay type list `pay_type`, e.g. `bank`, `alipay`, `wechat`, `paypal`, `swift`, `wu`.
	PayType string `json:"payType"`
	// JSON map of payment type -> user's payment method ID.
	PayTypeJson string `json:"pay_type_json,omitempty"`
	// Price type: `0` floating; `1` fixed.
	RateFixed string `json:"rateFixed,omitempty"`
	// Pass ad ID when editing; omit or empty when publishing a new ad.
	Oid string `json:"oid,omitempty"`
	// Minimum trade amount in `exchangeType`.
	MinAmount string `json:"minAmount"`
	// Maximum amount per trade in `exchangeType` fiat units.
	MaxAmount string `json:"maxAmount"`
	// Minimum counterparty VIP level; `0` means no requirement.
	TierLimit string `json:"tierLimit,omitempty"`
	// Minimum counterparty verification level; `0` means no limit.
	VerifiedLimit string `json:"verifiedLimit,omitempty"`
	// Minimum counterparty account age in days; `0` means no limit.
	RegTimeLimit string `json:"regTimeLimit,omitempty"`
	// Whether trading with the advertiser is restricted. `0`: no; `1`: yes.
	AdvertisersLimit string `json:"advertisersLimit,omitempty"`
	// Payment timeout in minutes.
	ExpireMin string `json:"expire_min,omitempty"`
	// Ad trading terms shown to the taker.
	TradeTips string `json:"trade_tips,omitempty"`
	// Auto-reply message after order creation.
	AutoReply string `json:"auto_reply,omitempty"`
	// Minimum completed orders for counterparty; `-1` unlimited.
	MinCompletedLimit string `json:"min_completed_limit,omitempty"`
	// Maximum completed orders for counterparty; `-1` unlimited.
	MaxCompletedLimit string `json:"max_completed_limit,omitempty"`
	// Counterparty minimum 30-day completion rate; `-1` means no limit.
	CompletedRateLimit string `json:"completed_rate_limit,omitempty"`
	// KYC nationality restriction; `-1` means no restriction.
	UserCountryLimit string `json:"user_country_limit,omitempty"`
	// Maximum concurrent orders allowed for the counterparty. `-1`: unlimited.
	UserOrderLimit string `json:"user_order_limit,omitempty"`
	// Floating price reference. `1`: platform reference; `2`: Gate reference; `3`: spot reference.
	RateReferenceId string `json:"rateReferenceId,omitempty"`
	// Absolute floating offset ratio, e.g. `0.5` means 0.5%.
	RateOffset string `json:"rateOffset,omitempty"`
	// Floating direction: `0` markup; `1` markdown.
	FloatTrend string `json:"float_trend,omitempty"`
	// Team payee UID; optional for non-team merchants.
	TeamPaymentUid string `json:"team_payment_uid,omitempty"`
}
