/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type Mt5Account struct {
	// Business Status Code; Non-zero Indicates Business Exception, Please Check Message
	Code int32 `json:"code,omitempty"`
	// Response message
	Message string `json:"message,omitempty"`
	// Server timestamp (milliseconds)
	Timestamp int64          `json:"timestamp,omitempty"`
	Data      Mt5AccountData `json:"data,omitempty"`
}
