/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Futures order
type MockFuturesOrder struct {
	// Perpetual contract name. Only USDT perpetual contracts for underlying currencies with active options trading are supported.
	Contract string `json:"contract"`
	// Contract quantity, representing the initial order quantity, not involved in actual settlement
	Size string `json:"size"`
	// Unfilled contract quantity, involved in actual calculation
	Left string `json:"left"`
}
