/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CreateEarnFixedTermLendResponse struct {
	// Return code, 0 means success
	Code int32 `json:"code,omitempty"`
	// Response message
	Message string                              `json:"message,omitempty"`
	Data    CreateEarnFixedTermLendResponseData `json:"data,omitempty"`
	// Response timestamp (in seconds)
	Timestamp int32 `json:"timestamp,omitempty"`
}
