/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// v4 interface unified error response
type HodlerAirdropV4ErrorResponse struct {
	// Error label
	Label string `json:"label"`
	// Error messages (multilingual)
	Message string `json:"message"`
}
