/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Auto invest plan portfolio item
type AutoInvestPortfolioItem struct {
	// Currency
	Asset string `json:"asset"`
	// Ratio
	Ratio string `json:"ratio"`
	// Accumulated investment
	CumInvest string `json:"cum_invest"`
	// AccumulatedPosition
	CumHold string `json:"cum_hold"`
	// Accumulated redemption
	CumRedeem string `json:"cum_redeem"`
	// Average Cost Price
	AvgPrice string `json:"avg_price"`
	// Redemption status
	RedeemStatus int64 `json:"redeem_status"`
	// LendingQuantity
	LendAmount string `json:"lend_amount"`
}
