/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 参与活动响应
type HodlerAirdropV4OrderResponse struct {
	// 获得空投的币种列表
	InterestCoin []string `json:"interest_coin"`
}
