/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse2001 struct {
	// Trading Pair
	Symbol string `json:"symbol"`
	// Last price
	LastPrice string `json:"last_price,omitempty"`
	// 24-hour opening price
	Open24h string `json:"open_24h,omitempty"`
	// 24h Low
	Low24h string `json:"low_24h,omitempty"`
	// 24h High
	High24h string `json:"high_24h,omitempty"`
	// 24-hour trading volume in base currency
	Volume24hBase string `json:"volume_24h_base,omitempty"`
	// 24-hour trading volume in quote currency
	Volume24hQuote string `json:"volume_24h_quote,omitempty"`
	// Mark price
	MarkPrice string `json:"mark_price,omitempty"`
	// Index price
	IndexPrice string `json:"index_price,omitempty"`
	// Open interest
	OpenInterest string `json:"open_interest,omitempty"`
	// Open interest (in quote currency)
	OpenInterestQuote string `json:"open_interest_quote,omitempty"`
	// Update timestamp
	Timestamp string `json:"timestamp"`
}
