/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// S3 POST Policy signature fields; send unchanged as form-data during direct upload
type OtcUploadPreUploadPolicyFields struct {
	// Plaintext temporary object path, identical to base64_decode(file_key)
	Key string `json:"key"`
	// Must match the decoded content_type from the pre-upload request
	ContentType string `json:"Content-Type"`
	// AWS temporary credential and scope; submit them unchanged during direct upload
	XAmzCredential string `json:"X-Amz-Credential"`
	// AWS signing algorithm; submit it unchanged during direct upload
	XAmzAlgorithm string `json:"X-Amz-Algorithm"`
	// AWS signing timestamp; submit it unchanged during direct upload
	XAmzDate string `json:"X-Amz-Date"`
	// Base64-encoded S3 POST Policy; submit it unchanged during direct upload
	Policy string `json:"Policy"`
	// S3 POST Policy signature; submit it unchanged during direct upload
	XAmzSignature string `json:"X-Amz-Signature"`
}
