/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// **仅用于预览** `OrderPreviewV1Req.to`。目标币种 + **比例 ratio**。 **禁止**与下单 `CreateParam` 混淆：下单的 `to` 必须使用 **`amount`**，没有 `ratio` 字段。
type PreviewToParam struct {
	// 目标币种符号；常与 config 中 `recommend_v2.*[].schemes[].name` 对应。
	Asset string `json:"asset"`
	// 该目标币种在组合中的权重比例，**十进制字符串**（如 `0.2`、`0.5`）。 常与 `GET /asset-swap/config` 的 `recommend_v2` 下某策略的 `schemes[].ratio` 一致。
	Ratio string `json:"ratio"`
}
