/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OtcBankCreateResponseData struct {
	// Bank card primary key in otc_rds.
	BankId int32 `json:"bank_id"`
	// Review status (e.g., pending review).
	Status int32 `json:"status"`
}
