/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Modify order price and take profit/stop loss parameters
type TradFiOrderUpdateRequest struct {
	// Price Description: - Required
	Price string `json:"price"`
	// Take Profit Price Description: - If not provided or set to \"0\": The original take profit price will be cleared - If you do not want to clear it, pass the original take profit price returned by the interface
	PriceTp *string `json:"price_tp,omitempty"`
	// Stop Loss Price Description: - If not provided or set to \"0\": The original stop loss price will be cleared - If you do not want to clear it, pass the original stop loss price returned by the interface
	PriceSl *string `json:"price_sl,omitempty"`
}
