/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// The result information returned after the termination strategy is successful.
type AiHubPortfolioStopData struct {
	StrategyId   string       `json:"strategy_id"`
	StrategyType StrategyType `json:"strategy_type"`
	// The current implementation returns `stopping`
	Status        string `json:"status"`
	ResultMessage string `json:"result_message"`
}
