/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type P2pTransactionActionResponse struct {
	Code      int32  `json:"code,omitempty"`
	Message   string `json:"message,omitempty"`
	Timestamp int32  `json:"timestamp,omitempty"`
}
