/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Create the request body of the contract grid strategy.
type FuturesGridCreateRequest struct {
	StrategyType string                  `json:"strategy_type"`
	Market       string                  `json:"market"`
	CreateParams FuturesGridCreateParams `json:"create_params"`
}
