/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CrossexAccountBookRecord struct {
	// Account Change Record ID
	Id string `json:"id"`
	// User ID
	UserId string `json:"user_id"`
	// Business ID. Its meaning varies by `statement_type`. TRANSACTION: order ID TRADING_FEE: order ID LIQUIDATION_FEE: liquidation order ID FUNDING_FEE: position ID and funding fee settlement time For other types, it is a system-generated processing ID with no business meaning
	BusinessId string `json:"business_id"`
	// Account book entry type `TRANSACTION`: trade `TRADING_FEE`: trading fee `FUNDING_FEE`: futures funding fee `LIQUIDATION_FEE`: liquidation fee `TRANSFER_IN`: transfer in `TRANSFER_OUT`: transfer out `BANKRUPT_COMPENSATION`: bankruptcy compensation `AUTO_REPAY`: automatic repayment of margin position liabilities `INTEREST_ISOLATED`: interest entry `ACCOUNT_MODE_CHANGE`: balance change caused by an account mode switch `KRAKEN_CONVERSION`: conversion of other margin currencies to cover a negative KRAKEN_USD balance `OTHER`: other
	StatementType string `json:"statement_type"`
	// Exchange
	ExchangeType string `json:"exchange_type"`
	// Currency
	Coin string `json:"coin"`
	// Trading Pair
	Symbol string `json:"symbol,omitempty"`
	// Change amount (positive values indicate an increase; negative values indicate a decrease)
	Change string `json:"change"`
	// Balance after change
	Balance string `json:"balance"`
	// Created time
	CreateTime string `json:"create_time"`
}
