/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Place order request parameters
type TradFiSpotOrderRequest struct {
	// Order quantity
	Volume string `json:"volume"`
	// Symbol
	Symbol string `json:"symbol"`
	// Side (1=sell, 2=buy)
	Side int32 `json:"side"`
	// Price type (market = market order, limit = limit order)
	PriceType string `json:"price_type"`
	// Trading session. Limit orders support only All, while market orders support only Regular.
	TradingSession string `json:"trading_session"`
	// Time in force. - day: Day order.
	TimeInForce string `json:"time_in_force"`
	// Order price, used for limit orders
	Price string `json:"price,omitempty"`
	// Client-defined order ID
	ClientOrderId string `json:"client_order_id,omitempty"`
}
