/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse2005Data struct {
	// Bank ID (required for order placement)
	Id              string `json:"id"`
	BankAccountName string `json:"bank_account_name"`
	BankName        string `json:"bank_name"`
	BankCountry     string `json:"bank_country"`
	BankAddress     string `json:"bank_address"`
	BankCode        string `json:"bank_code"`
	BranchCode      string `json:"branch_code"`
}
