/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type Error struct {
	// Business status code, non-empty indicates request exception, please refer to TradFi error enumeration in documentation
	Label string `json:"label,omitempty"`
	// Return message, returned when request error occurs
	Message string `json:"message,omitempty"`
	// Server timestamp (milliseconds)
	Timestamp int64 `json:"timestamp,omitempty"`
}
