/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Get beginner task list response
type ApiResponseExSkillGetBeginnerTaskListResp struct {
	// Business error code: 0 = success, 1007 = no task data, 1008 = not logged in
	Code int32 `json:"code,omitempty"`
	// Error identifier code. Empty string on success, machine-readable error label on error
	Label string `json:"label,omitempty"`
	// Error description
	Message string                                        `json:"message,omitempty"`
	Data    ApiResponseExSkillGetBeginnerTaskListRespData `json:"data,omitempty"`
	// Server timestamp (milliseconds)
	Timestamp int64 `json:"timestamp,omitempty"`
}
