/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type DualGetPlans struct {
	// Product ID
	Id int32 `json:"id,omitempty"`
	// Product Name
	InstrumentName string `json:"instrument_name,omitempty"`
	// Investment Token
	InvestCurrency string `json:"invest_currency,omitempty"`
	// Strike Token
	ExerciseCurrency string `json:"exercise_currency,omitempty"`
	// Strike price
	ExercisePrice float64 `json:"exercise_price,omitempty"`
	// Settlement time
	DeliveryTime int32 `json:"delivery_time,omitempty"`
	// Minimum Units
	MinCopies int32 `json:"min_copies,omitempty"`
	// Maximum Units
	MaxCopies int32 `json:"max_copies,omitempty"`
	// Value Per Unit
	PerValue string `json:"per_value,omitempty"`
	// Annual Yield
	ApyDisplay string `json:"apy_display,omitempty"`
	// Start Time
	StartTime int32 `json:"start_time,omitempty"`
	// End time
	EndTime int32 `json:"end_time,omitempty"`
	// Status:   `NOTSTARTED`-Not Started  `ONGOING`-In Progress  `ENDED`-Ended
	Status string `json:"status,omitempty"`
}
