/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type StopAllTrailOrders struct {
	// Contract name
	Contract string `json:"contract,omitempty"`
	// Associated position, if provided, only cancel orders associated with this position, 1-long, 2-short
	RelatedPosition int32 `json:"related_position,omitempty"`
}
