/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse202 struct {
	// Requested futures position mode to modify (SINGLE/DUAL)
	PositionMode string `json:"position_mode,omitempty"`
	// Requested account mode to modify (CROSS_EXCHANGE/ISOLATED_EXCHANGE, default: CROSS_EXCHANGE)
	AccountMode string `json:"account_mode,omitempty"`
	// Requested exchange to modify (BINANCE/OKX/GATE/CROSSEX; when account mode is ISOLATED_EXCHANGE, the exchange must be specified to modify futures position mode)
	ExchangeType string `json:"exchange_type,omitempty"`
}
