/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 单条策略推荐信息。
type AiHubRecommendation struct {
	RecommendationId string       `json:"recommendation_id"`
	Market           string       `json:"market"`
	StrategyType     StrategyType `json:"strategy_type"`
	StrategyName     string       `json:"strategy_name"`
	BacktestApr      string       `json:"backtest_apr,omitempty"`
	MaxDrawdown      string       `json:"max_drawdown,omitempty"`
	Summary          string       `json:"summary"`
	// 推荐参数预览；按策略类型动态变化
	StrategyParamsPreview map[string]interface{} `json:"strategy_params_preview,omitempty"`
}
