/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Borrowing
type UniLoan struct {
	// Currency
	Currency string `json:"currency,omitempty"`
	// Currency pair
	CurrencyPair string `json:"currency_pair,omitempty"`
	// Amount to Repay
	Amount string `json:"amount,omitempty"`
	// Loan type: platform borrowing - platform, margin borrowing - margin
	Type string `json:"type,omitempty"`
	// Created time
	CreateTime int64 `json:"create_time,omitempty"`
	// Last Update Time
	UpdateTime int64 `json:"update_time,omitempty"`
}
