/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OtcBankSupplementChecklistItem struct {
	// Material item code, corresponding to the top-level key of `relationship_proof`
	Code string `json:"code"`
	Zh   string `json:"zh,omitempty"`
	En   string `json:"en,omitempty"`
	// Whether required
	Required bool `json:"required"`
}
