/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Currency account information
type MarginAccountCurrency struct {
	// Currency name
	Currency string `json:"currency,omitempty"`
	// Amount available for margin trading, available = margin + borrowed
	Available string `json:"available,omitempty"`
	// Frozen funds, such as amounts already placed in margin market for order trading
	Locked string `json:"locked,omitempty"`
	// Borrowed funds
	Borrowed string `json:"borrowed,omitempty"`
	// Unpaid interest
	Interest string `json:"interest,omitempty"`
}
