/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type QuickRepaymentRequest struct {
	// Liability currencies
	DebtCurrencies []string `json:"debt_currencies"`
	// Currencies to repay with
	AvailableCurrencies []string `json:"available_currencies"`
}
