/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Liquidation details (null for normal close)
type PositionHistoryListDataCloseDetail struct {
	// Margin ratio (multiplied by 100)
	MarginLevel string `json:"margin_level,omitempty"`
	// Position margin
	Margin string `json:"margin,omitempty"`
	// Net equity
	Equity string `json:"equity,omitempty"`
	// Liquidation ratio (multiplied by 100)
	StopOutLevel string `json:"stop_out_level,omitempty"`
}
