/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Contract position details (historical data)
type PositionTimerange struct {
	// Futures contract
	Contract string `json:"contract,omitempty"`
	// Position size
	Size string `json:"size,omitempty"`
	// Position leverage. 0 means cross margin; positive number means isolated margin
	Leverage string `json:"leverage,omitempty"`
	// Position risk limit
	RiskLimit string `json:"risk_limit,omitempty"`
	// the maximum permissible leverage given to the current positon value: the higher positon value, the lower maximum permissible leverage
	LeverageMax string `json:"leverage_max,omitempty"`
	// The maintenance margin rate of the first tier of risk limit sheet
	MaintenanceRate string `json:"maintenance_rate,omitempty"`
	// Position margin
	Margin string `json:"margin,omitempty"`
	// Liquidation price
	LiqPrice string `json:"liq_price,omitempty"`
	// Realized PnL
	RealisedPnl string `json:"realised_pnl,omitempty"`
	// Total realized PnL from closed positions
	HistoryPnl string `json:"history_pnl,omitempty"`
	// PNL of last position close
	LastClosePnl string `json:"last_close_pnl,omitempty"`
	// Realized POINT PNL
	RealisedPoint string `json:"realised_point,omitempty"`
	// History realized POINT PNL
	HistoryPoint string `json:"history_point,omitempty"`
	// Position mode, including: - `single`: One-way Mode - `dual_long`: Long position in Hedge Mode - `dual_short`: Short position in Hedge Mode
	Mode string `json:"mode,omitempty"`
	// Cross margin leverage (valid only when `leverage` is 0)
	CrossLeverageLimit string `json:"cross_leverage_limit,omitempty"`
	// Entry price
	EntryPrice string `json:"entry_price,omitempty"`
	// Timestamp
	Time int64 `json:"time,omitempty"`
}
