/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse20011Data struct {
	// Payment method type
	PayType string `json:"pay_type,omitempty"`
	// Payment method name
	PayName string `json:"pay_name,omitempty"`
	// User's currently bound payment method (primary key ID)
	Ids  []int32                   `json:"ids,omitempty"`
	List []InlineResponse20011List `json:"list,omitempty"`
}
