/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Cancel order request
type CancelOrder struct {
	TradeId    string `json:"trade_id"`
	ReasonId   string `json:"reason_id,omitempty"`
	ReasonMemo string `json:"reason_memo,omitempty"`
}
