/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Request body for stopping a chase order
type StopChaseOrderReq struct {
	// Order ID. Either id or text must be provided
	Id string `json:"id,omitempty"`
	// Custom text. Required only when id is 0 or omitted
	Text string `json:"text,omitempty"`
	// Overridden by the path parameter
	Settle string `json:"settle,omitempty"`
}
