/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Announcement articles and total count
type AnnouncementArticleListData struct {
	// Announcement article list
	List []AnnouncementArticle `json:"list"`
	// Total number of announcement articles.
	Total int32 `json:"total"`
}
