/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Returned when code=0; empty object {} otherwise
type ListUserCouponsResponseData struct {
	// Whether there is a next page. `true` means more data is available. Pass the `id` of the last record as `last_id` and `expire_time_order_by` as `expire_time` in the next request
	NextPage bool `json:"next_page,omitempty"`
	// Coupon object array, see field details below
	List []ListUserCouponsResponseDataList `json:"list,omitempty"`
}
