/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Bonus reward campaign information
type FixedTermBonusInfo struct {
	// Activity ID
	Id int32 `json:"id,omitempty"`
	// Associated product ID
	ProductId int32 `json:"product_id,omitempty"`
	// Product currency
	Asset string `json:"asset,omitempty"`
	// Reward currency
	BonusAsset string `json:"bonus_asset,omitempty"`
	// KYC level restrictions, comma-separated
	KycLimit string `json:"kyc_limit,omitempty"`
	// Tiered annual interest rate
	LadderApr []LadderApr `json:"ladder_apr,omitempty"`
	// Total reward amount
	TotalBonusAmount string `json:"total_bonus_amount,omitempty"`
	// Maximum reward per user
	UserTotalBonusAmount string `json:"user_total_bonus_amount,omitempty"`
	// Activity status: 1 for unlisted, 2 for listed, 3 for delisted
	Status int32 `json:"status,omitempty"`
	// Activity start time
	StartTime string `json:"start_time,omitempty"`
	// Activity end time
	EndTime string `json:"end_time,omitempty"`
	// Created time
	CreateTime string `json:"create_time,omitempty"`
	// Activity start timestamp (in seconds)
	StartAt int32 `json:"start_at,omitempty"`
	// Activity end timestamp (in seconds)
	EndAt int32 `json:"end_at,omitempty"`
	// Total rewards distributed
	TotalIssuedAmount string `json:"total_issued_amount,omitempty"`
	// Total rewards distributed to the user
	UserTotalIssuedAmount string `json:"user_total_issued_amount,omitempty"`
	// Reward currency price (denominated in USDT)
	BonusAssetPrice string `json:"bonus_asset_price,omitempty"`
	// Product currency price (denominated in USDT)
	ProductAssetPrice string `json:"product_asset_price,omitempty"`
	// Product base annual interest rate
	ProductYearRate string `json:"product_year_rate,omitempty"`
}
