/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Get market ads list request
type AdsListRequest struct {
	// Cryptocurrency
	Asset string `json:"asset"`
	// Fiat currency
	FiatUnit string `json:"fiat_unit"`
	// Buy/Sell, sell/buy
	TradeType string `json:"trade_type"`
}
