/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type TransactionList2 struct {
	Data      TransactionList2Data `json:"data,omitempty"`
	Timestamp int64                `json:"timestamp,omitempty"`
}
