/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 现货马丁策略的创建参数。
type SpotMartingaleCreateParams struct {
	InvestAmount       string `json:"invest_amount"`
	PriceDeviation     string `json:"price_deviation"`
	MaxOrders          int32  `json:"max_orders"`
	TakeProfitRatio    string `json:"take_profit_ratio"`
	StopLossPrice      string `json:"stop_loss_price,omitempty"`
	ProfitSharingRatio string `json:"profit_sharing_ratio,omitempty"`
}
