/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type ListActivitiesResponse struct {
	// Response status code, 0 means success
	Code int32 `json:"code"`
	// 响应消息，成功时为 \"success\"
	Message string                     `json:"message"`
	Data    ListActivitiesResponseData `json:"data"`
	// Server timestamp (milliseconds)
	Timestamp int64 `json:"timestamp"`
}
