/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Close position request parameters
type TradFiSpotClosePositionRequest struct {
	// Symbol
	Symbol string `json:"symbol"`
	// Close quantity; required for partial close
	CloseVolume string `json:"close_volume,omitempty"`
	// Close type (1=partial close, 2=close all)
	CloseType int32 `json:"close_type"`
}
