/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse201 struct {
	// Status code, 0 means success
	Code int32 `json:"code,omitempty"`
	// Response message
	Message string                `json:"message,omitempty"`
	Data    InlineResponse201Data `json:"data,omitempty"`
	// Response timestamp (milliseconds)
	Timestamp int64 `json:"timestamp,omitempty"`
}
