/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Creation parameters for the spot grid strategy.
type SpotGridCreateParams struct {
	// Amount of investment
	Money string `json:"money"`
	// Range lower limit
	LowPrice string `json:"low_price"`
	// Range upper limit
	HighPrice string `json:"high_price"`
	// Number of grids
	GridNum            int32  `json:"grid_num"`
	PriceType          int32  `json:"price_type"`
	TriggerPrice       string `json:"trigger_price,omitempty"`
	StopProfit         string `json:"stop_profit,omitempty"`
	StopLoss           string `json:"stop_loss,omitempty"`
	ProfitSharingRatio string `json:"profit_sharing_ratio,omitempty"`
	IsUseBase          bool   `json:"is_use_base,omitempty"`
}
