/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse20023Data struct {
	// Serial number
	Index int32 `json:"index,omitempty"`
	// Cryptocurrency
	Asset string `json:"asset,omitempty"`
	// Fiat currency
	FiatUnit string `json:"fiat_unit,omitempty"`
	// Ad ID
	AdvNo int32 `json:"adv_no,omitempty"`
	// Price
	Price string `json:"price,omitempty"`
	// Maximum Cryptocurrency Amount
	MaxSingleTransAmount string `json:"max_single_trans_amount,omitempty"`
	// Minimum Cryptocurrency Amount
	MinSingleTransAmount string `json:"min_single_trans_amount,omitempty"`
	// Advertiser Nickname
	NickName string `json:"nick_name,omitempty"`
}
