/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// DiscoverScene 策略推荐接口支持的场景枚举。
type DiscoverScene string

// List of DiscoverScene
const (
	TOP1    DiscoverScene = "top1"
	BUNDLE  DiscoverScene = "bundle"
	FILTER  DiscoverScene = "filter"
	REFRESH DiscoverScene = "refresh"
)
