/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type FuturesAccountBook struct {
	// Change time
	Time float64 `json:"time,omitempty"`
	// Change amount
	Change string `json:"change,omitempty"`
	// Balance after change
	Balance string `json:"balance,omitempty"`
	// Change types:  - dnw: Deposit and withdrawal - pnl: Profit and loss from position reduction - fee: Trading fees - refr: Referrer rebates - fund: Funding fees - point_dnw: Point card deposit and withdrawal - point_fee: Point card trading fees - point_refr: Point card referrer rebates - bonus_offset: Trial fund deduction
	Type string `json:"type,omitempty"`
	// Comment
	Text string `json:"text,omitempty"`
	// Futures contract, the field is only available for data after 2023-10-30
	Contract string `json:"contract,omitempty"`
	// trade id
	TradeId string `json:"trade_id,omitempty"`
	// Account change record ID
	Id string `json:"id,omitempty"`
}
