/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Announcement article language
type AnnouncementArticleLanguage struct {
	// Language code, for example \"cn\".
	Code string `json:"code"`
	// Language name
	Name string `json:"name"`
}
