/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OptionsMyTrade struct {
	// Fill ID
	Id int64 `json:"id,omitempty"`
	// Fill Time
	CreateTime float64 `json:"create_time,omitempty"`
	// Options contract name
	Contract string `json:"contract,omitempty"`
	// Related order ID
	OrderId int32 `json:"order_id,omitempty"`
	// Trading size
	Size int64 `json:"size,omitempty"`
	// Trade price (quote currency)
	Price string `json:"price,omitempty"`
	// The forward futures price corresponding to the delivery date
	UnderlyingPrice string `json:"underlying_price,omitempty"`
	// Trade role. taker - taker, maker - maker
	Role string `json:"role,omitempty"`
}
