/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type OtcBankSupplementChecklistResponse struct {
	Code      int32                                  `json:"code"`
	Message   string                                 `json:"message"`
	Data      OtcBankSupplementChecklistResponseData `json:"data"`
	Timestamp int32                                  `json:"timestamp,omitempty"`
}
