/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type UpdateTrailOrder struct {
	// Order ID
	Id int64 `json:"id"`
	// Total trading quantity in contracts, positive for buy, negative for sell, 0 means no modification
	Amount string `json:"amount,omitempty"`
	// Activation price, 0 means trigger immediately, empty means no modification
	ActivationPrice string `json:"activation_price,omitempty"`
	// true: activate when market price >= activation price, false: <= activation price, empty means no modification
	IsGteStr string `json:"is_gte_str,omitempty"`
	// Activation price type, not provided or 0 means no modification, 1-latest price, 2-index price, 3-mark price
	PriceType int32 `json:"price_type,omitempty"`
	// Callback ratio or price distance, e.g., `0.1` or `0.1%`; empty means no modification
	PriceOffset string `json:"price_offset,omitempty"`
}
