/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse20011Data struct {
	Pn      int32                         `json:"pn"`
	Ps      int32                         `json:"ps"`
	TotalPn int32                         `json:"total_pn"`
	Count   int32                         `json:"count"`
	List    []InlineResponse20011DataList `json:"list"`
}
