/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Margin account information for a trading pair. `base` corresponds to base currency account information, `quote` corresponds to quote currency account information
type MarginAccount struct {
	// Currency pair
	CurrencyPair string `json:"currency_pair,omitempty"`
	// Account type: risk - risk rate account, mmr - maintenance margin rate account, inactive - market not activated
	AccountType string `json:"account_type,omitempty"`
	// User's current market leverage multiplier
	Leverage string `json:"leverage,omitempty"`
	// Whether the account is locked
	Locked bool `json:"locked,omitempty"`
	// Current risk rate of the margin account (returned when the account is a risk rate account)
	Risk string `json:"risk,omitempty"`
	// Leveraged Account Current Maintenance Margin Rate (returned when the Account is Account)
	Mmr   string                `json:"mmr,omitempty"`
	Base  MarginAccountCurrency `json:"base,omitempty"`
	Quote MarginAccountCurrency `json:"quote,omitempty"`
}
