/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Sub-broker information
type BrokerCommissionSubBrokerInfo struct {
	// Sub-broker user ID
	UserId int64 `json:"user_id,omitempty"`
	// Sub-broker original commission rate
	OriginalCommissionRate string `json:"original_commission_rate,omitempty"`
	// Sub-broker relative commission rate
	RelativeCommissionRate string `json:"relative_commission_rate,omitempty"`
	// Sub-broker actual commission rate
	CommissionRate string `json:"commission_rate,omitempty"`
}
