/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 策略推荐结果数据。
type AiHubDiscoverData struct {
	Scene           DiscoverScene         `json:"scene"`
	Recommendations []AiHubRecommendation `json:"recommendations"`
	// 本期不支持的筛选条件
	UnsupportedFilters []string `json:"unsupported_filters"`
}
