/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse20017Data struct {
	// Message List
	Messages []InlineResponse20017DataMessages `json:"messages"`
	// Payment tip (displayed on homepage only)
	Memo string `json:"memo"`
	// Whether historical records exist
	HasHistory bool `json:"has_history"`
	// Order ID
	Txid int32 `json:"txid"`
	// Timestamp of the latest message
	SRVTM int32 `json:"SRVTM"`
	// Order Status
	OrderStatus string `json:"order_status"`
}
