/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Personal supplement `multipart/form-data`. File field names are fixed: `id_document_front`, `id_document_back`, `address_proof` (aligned with the checklist `code`); the optional string field `relationship_proof` (JSON text) is merged with the upload result.
type OtcBankPersonalSupplementMultipartRequest struct {
	BankId string `json:"bank_id"`
	// ID document front-side file content (multipart file field, binary/Base64)
	IdDocumentFront string `json:"id_document_front"`
	// ID document back-side file content (multipart file field, binary/Base64)
	IdDocumentBack string `json:"id_document_back"`
	// Proof-of-address file content (multipart file field, binary/Base64)
	AddressProof string `json:"address_proof"`
}
