/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// FuturesDirection 合约类策略支持的方向枚举。
type FuturesDirection string

// List of FuturesDirection
const (
	LONG    FuturesDirection = "long"
	SHORT   FuturesDirection = "short"
	NEUTRAL FuturesDirection = "neutral"
)
