/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// 用户空投发放记录单项
type HodlerAirdropV4UserAirdropRecord struct {
	// Product ID
	HodlerId string `json:"hodler_id"`
	// 空投币种
	Asset string `json:"asset"`
	// 基础空投金额
	ReceiveAmountBase string `json:"receive_amount_base,omitempty"`
	// 额外空投金额（余币宝加成）
	ReceiveAmountExt string `json:"receive_amount_ext,omitempty"`
	// 空投发放时间，格式 Y-m-d H:i:s，UTC；未发放时可能为空字符串
	DeliveryTimest string `json:"delivery_timest"`
	// 自动兑换状态，0未兑换 1已兑换为GT
	Exchange string `json:"exchange,omitempty"`
}
