/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type ListEarnFixedTermLendsResponse struct {
	// Return code, 0 means success
	Code int32 `json:"code"`
	// Response message
	Message string                             `json:"message"`
	Data    ListEarnFixedTermLendsResponseData `json:"data"`
	// Response timestamp (in seconds)
	Timestamp int32 `json:"timestamp"`
}
