/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

// Response data
type OrderLogData struct {
	// Order ID
	OrderId int32 `json:"order_id,omitempty"`
	// logID
	LogId int32 `json:"log_id,omitempty"`
	// Trading pair of the order
	Symbol string `json:"symbol,omitempty"`
	// Trade type (market=market price, trigger=trigger price)
	PriceType string `json:"price_type,omitempty"`
	// Order status code (1=placed, 2=canceled, 3=partially filled, 4=filled, 5=rejected)
	State int32 `json:"state,omitempty"`
	// Order side (1=sell, 2=buy)
	Side int32 `json:"side,omitempty"`
	// Order volume
	Volume string `json:"volume,omitempty"`
	// Average fill price
	Price string `json:"price,omitempty"`
}
