/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type InlineResponse2002Data struct {
	// BUY (on-ramp) or SELL (off-ramp)
	Type string `json:"type"`
	// Payment currency
	PayCoin string `json:"pay_coin"`
	// Currency
	GetCoin string `json:"get_coin"`
	// Payment amount
	PayAmount string `json:"pay_amount"`
	// Redemption Amount
	GetAmount string `json:"get_amount"`
	// Exchange rate
	Rate string `json:"rate"`
	// Reciprocal of the exchange rate
	RateReci string `json:"rate_reci"`
	// Promotion code
	PromotionCode string `json:"promotion_code"`
	// Quote method
	Side string `json:"side"`
	// Order type: FIAT (fiat) / STABLE (stablecoin)
	OrderType string `json:"order_type"`
	// Quote token required when placing an order
	QuoteToken string `json:"quote_token"`
}
