/*
 * Gate API
 *
 * Welcome to Gate API APIv4 provides operations related to spot, margin, and contract trading, including public interfaces for querying market data and authenticated private interfaces for implementing API-based automated trading.
 *
 * Contact: support@mail.gate.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package gateapi

type CandyDropV4ActivityRulesCd03 struct {
	// 项目/币种名称
	Currency string `json:"currency,omitempty"`
	// 总奖池
	TotalRewards string `json:"total_rewards,omitempty"`
	// 活动开始时间（UTC格式化）
	StartTime string `json:"start_time,omitempty"`
	// 活动结束时间（UTC格式化）
	EndTime string `json:"end_time,omitempty"`
	// 奖池列表
	PrizePools []CandyDropV4PrizePoolCd03 `json:"prize_pools,omitempty"`
}
